

# Load

Load the data from the dropbox


```{r}


shared_dropbox_dir <- "C:/Users/al/Dropbox/New Graph/"


files_to_read2 <- list.files(paste0(shared_dropbox_dir,"fiss/2020-11-16/"), full.names = T)
files_names2 <- list.files(paste0(shared_dropbox_dir,"fiss/2020-11-16/"), full.names = F) %>% tools::file_path_sans_ext()


##mini function to change column names to lower case
names_to_lower <- function(dat){
  dat %>% 
  purrr::set_names(nm = stringr::str_to_lower(names(dat)))
}


d <- files_to_read %>% 
  map(readr::read_csv) %>% 
  map(names_to_lower) %>% 
  purrr::set_names(nm = files_names)

```


```{r}
details <- d %>% pluck('details')
visits <- d %>% pluck('visits')
habitat <- d %>% pluck('habitat')
counts <- d %>% pluck('counts')
```

make a table that has all the info we want in one place for the summarized fish

```{r}
d_sum <- left_join(
  d %>% pluck('counts'),
  d %>% pluck('visits'),
  by = 'key'
  ) %>% 
  left_join(
    .,
    d %>% pluck('habitat'),
    by = 'key'
  ) %>% 
##clean it up and grab a density
  filter(!is.na(fishing_area_length) & 
           !is.na(fishing_area_width) &
           !is.na(utm_easting) &
           !is.na(utm_northing) &
           utm_zone > 0 &
           haul_or_pass == 1 &
           species_code %in% c('RB', 'BT', 'GR', 'CH', 'CO', 'SK', 'WCT', 'ST')) %>%
    #For the sake of a first run lets keep only the first passes from sites that have multiple passes
  mutate(density_100m = number_caught/(fishing_area_length * fishing_area_width) * 100)
  
```


We need in spatial format to tie to the FWA so lets put everything in albers and add the X and Y to the dataframe

```{r}

##function to transform to coodinate system
utm_to_coord <- function(dat, crs_to = 3005){
  crs_from = 26900 + dat %>% slice(1) %>% pull(utm_zone) ##we are assuming that the utm_zone is the same for all rows
  dat %>% 
    sf::st_as_sf(coords = c('utm_easting', 'utm_northing'), crs = crs_from , remove = F) %>% 
    sf::st_transform(crs = crs_to) %>% 
    mutate(x = st_coordinates(.)[,1],
           y = st_coordinates(.)[,2]) %>% 
    sf::st_drop_geometry()
}


d_sum_dens_albers <- d_sum_dens %>% 
  dplyr::group_split(utm_zone) %>% 
  map(utm_to_coord) %>% 
  bind_rows()



```



Lets have a look at what we have by species
```{r}
sum_by_sp <- d_sum %>% 
  group_by(species_code) %>% 
  summarise(n = n(), 
            dens_min = min(density_100m, na.rm = T),
            dens_max = max(density_100m, na.rm = T),
            dens_med = median(density_100m, na.rm = T))

weird <- d_sum %>% 
  filter(density_100m > 500)

```

